/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRemindersRouteImport } from './routes/_app/reminders'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppHealthRouteImport } from './routes/_app/health'
import { Route as AppEmailHelperRouteImport } from './routes/_app/email-helper'
import { Route as AppBureaucracyRouteImport } from './routes/_app/bureaucracy'
import { Route as AppAssistantRouteImport } from './routes/_app/assistant'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailHelperRoute = AppEmailHelperRouteImport.update({
  id: '/email-helper',
  path: '/email-helper',
  getParentRoute: () => AppRoute,
} as any)
const AppBureaucracyRoute = AppBureaucracyRouteImport.update({
  id: '/bureaucracy',
  path: '/bureaucracy',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/assistant': typeof AppAssistantRoute
  '/bureaucracy': typeof AppBureaucracyRoute
  '/email-helper': typeof AppEmailHelperRoute
  '/health': typeof AppHealthRoute
  '/jobs': typeof AppJobsRoute
  '/reminders': typeof AppRemindersRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/assistant': typeof AppAssistantRoute
  '/bureaucracy': typeof AppBureaucracyRoute
  '/email-helper': typeof AppEmailHelperRoute
  '/health': typeof AppHealthRoute
  '/jobs': typeof AppJobsRoute
  '/reminders': typeof AppRemindersRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/bureaucracy': typeof AppBureaucracyRoute
  '/_app/email-helper': typeof AppEmailHelperRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/reminders': typeof AppRemindersRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assistant'
    | '/bureaucracy'
    | '/email-helper'
    | '/health'
    | '/jobs'
    | '/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/assistant'
    | '/bureaucracy'
    | '/email-helper'
    | '/health'
    | '/jobs'
    | '/reminders'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/assistant'
    | '/_app/bureaucracy'
    | '/_app/email-helper'
    | '/_app/health'
    | '/_app/jobs'
    | '/_app/reminders'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reminders': {
      id: '/_app/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email-helper': {
      id: '/_app/email-helper'
      path: '/email-helper'
      fullPath: '/email-helper'
      preLoaderRoute: typeof AppEmailHelperRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bureaucracy': {
      id: '/_app/bureaucracy'
      path: '/bureaucracy'
      fullPath: '/bureaucracy'
      preLoaderRoute: typeof AppBureaucracyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppBureaucracyRoute: typeof AppBureaucracyRoute
  AppEmailHelperRoute: typeof AppEmailHelperRoute
  AppHealthRoute: typeof AppHealthRoute
  AppJobsRoute: typeof AppJobsRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppBureaucracyRoute: AppBureaucracyRoute,
  AppEmailHelperRoute: AppEmailHelperRoute,
  AppHealthRoute: AppHealthRoute,
  AppJobsRoute: AppJobsRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
